server:
  port: 9453
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mysql://localhost:3306/around?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1s
    lettuce:
      shutdown-timeout: 5s
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 8
  mail:
    host: smtp.qq.com
    username: 940121265@qq.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  configuration:
    cache-enabled: false
